### ISSUE TITLE
Command to run Jupyter Notebook

### ISSUE THREAD

**Issue by dinel** [brianspiering/word2vec-talk#1]
Hello,

The documentation says that you need to type `Jupyter Notebook`. I don't know whether it is a Windows vs. Linux thing, but on my Fedora Linux the command is lower case `jupyter Notebook`.

Cheers

**Comment by brianspiering** [comment]
You are right. It is better to be `jupyter notebook`. I have pushed a fix.

I was sloppy, those commands are the same on MacOS.
